apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flask-hello-world.fullname" . }}
  labels:
    {{- include "flask-hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flask-hello-world.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flask-hello-world.name" . }}
    spec:
      containers:
        - name: {{ include "flask-hello-world.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080  # Change the internal port to 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: http  # Use the internal port for liveness probe
              scheme: HTTPS  # Specify HTTPS for liveness probe
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http  # Use the internal port for readiness probe
              scheme: HTTPS  # Specify HTTPS for readiness probe
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

